ERROR: try to authenticate the app, receive "v1_retired" response
1. Changed just enough code in `client.py` and `session.py` to make the
v2 API calls needed to get through the authentication process.

2. Added `@v2_ready` decorator in client.py so we can mark methods as
we convert them.

3. Because of terse error responses being returned from the DropBox v2
API, while trying to get app authentication to work I added a lot of
`log_debug` messages around the http request and response activity
that happens in the RESTClientObject#request() method [file: rest.py].

4. Enhanced `ErrorResponse` exception class so that it provides
better information when it is raised.